#!/bin/bash

cd build-machine

vagrant status --machine-readable | grep state,running > /dev/null
if [ $? -ne 0 ]; then
    vagrant up
fi

vagrant ssh -c "source /home/vagrant/miniconda2/bin/activate build; cd /project_dir; gordon build"
