---
project: skunk
default-region: us-west-2
code-bucket: gordon-skunk-69d5f387
apps:
  - gordon.contrib.lambdas
  - pepe


apigateway:
  helloworldapi:
    description: My Api example
    resources:
      /:
        methods: GET
        integration:
          lambda: pepe.helloworld
