---
project: skunk
default-region: us-east-1
code-bucket: gordon-skunk-69d5f387
apps:
  - gordon.contrib.lambdas
  - backend

apigateway:
  tumalowapi:
    description: Tumalow API
    resources:
      /:
        methods: POST
        integration:
          lambda: backend.oracle
