lambdas:
  oracle: # lambda name
    description: Function that responds to what the pi should do next
    code: .
    handler: oracle.handler
    runtime: python2.7
    timeout: 31
    memory: 128
    build:
      - cp -Rf * {target}
      - docker run --rm -v {target}:/var/task -v {project_path}/tCass:/tCass lambci/lambda:build-python2.7 pip install -r requirements.txt -t /var/task
    policies:
      write_dynamo:
        Version: "2012-10-17"
        Statement:
          -
            Action:
              - "dynamodb:DescribeTable"
              - "dynamodb:GetItem"
              - "dynamodb:PutItem"
              - "dynamodb:Query"
              - "dynamodb:Scan"
              - "dynamodb:UpdateItem"
            Resource: "*"
            Effect: "Allow"
