lambdas:
  oracle: # lambda name
    description: Function that responds to what the pi should do next
    code: oracle.py

# lambdas:
#   helloworld: # lambda name
#     code: helloworld # folder name
#     handler: code.handler # file.method_name
#     runtime: python
#     #description: Simple functions in python which says hello
#     #role:
#     #memory:
